object Versions {

    const val GRADLE_PLUGIN_VERSION = "3.6.3"
    const val KOTLIN_VERSION = "1.3.70"
    const val BUILD_TOOLS_VERSION = "29.0.2"
    const val RETROFIT_VERSION = "2.8.1"
    const val ROOM_VERSION = "2.2.5"
    const val LIFECYCLE_VERSION = "2.2.0"
    const val COROUTINE_VERSION = "1.3.5"
    const val APP_COMPAT_VERSION = "1.0.0-beta01"
    const val MATERIAL_VERSION = "1.2.0-alpha06"
    const val CORE_KTX_VERSION = "1.3.0-rc01"
    const val JUNIT_VERSION = "4.12"
    const val TEST_RUNNER_VERSION = "1.1.0-alpha4"
    const val ESPRESSO_VERSION = "3.1.0-alpha4"
    const val KOTLIN_SERIALIZATION_VERSION = "0.20.0"
    const val KOTLIN_SERIALIZATION_CONVERTER_VERSION = "0.5.0"
    const val KOIN_VERSION = "2.1.5"
    const val TRANSITION_VERSION = "1.3.1"
    const val RECYCLER_VIEW_VERSION = "1.1.0"
    const val EPOXY_VERSION = "3.8.0"
    const val LOCATION_PROVIDER_VERSION = "17.0.0"
    const val PICASSO_VERSION = "2.71828"
    const val ANDROIDX_LEGACY_SUPPORT_VERSION = "1.0.0"
    const val CONSTRAINT_LAYOUT_VERSION = "1.1.3"

}